package main

const tmplGoMod = `module %s

go 1.25
`

const tmplMain = `package main

import (
	"log"

	"github.com/Ovi1kanobe/pocketkit"

	// Committed migrations are the schema's source of truth. Blank-importing
	// them here is what makes a fresh clone rebuild the exact same database.
	_ "%s/migrations"
)

func main() {
	app := pocketkit.New()

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
`

const tmplPing = `// Package ping answers GET /api/ping.
//
// The directory decides the URL and the file name decides the method, so this
// file needs no registration anywhere. The handler is named after its method,
// because every method file in a directory shares one Go package. Its
// signature is stock PocketBase.
package ping

import (
	"net/http"

	"github.com/pocketbase/pocketbase/core"
)

// The directive below opts this route out of pocketkit's default auth
// requirement. Remove it and the route requires a signed-in user.
//
//pocketkit:public
func GET(e *core.RequestEvent) error {
	return e.JSON(http.StatusOK, map[string]string{"status": "ok"})
}
`

const tmplMigrationsDoc = `// Package migrations holds this app's schema history.
//
// Schema changes made in the superuser dashboard are written here automatically
// as Go migrations. Commit them: they, not pb_data, are the source of truth.
package migrations
`

const tmplGitignore = `# PocketBase runtime data. The schema lives in migrations/, not here.
pb_data/

# Built frontend, served by PocketBase at runtime.
frontend/build/
frontend/.svelte-kit/
node_modules/

# Generated wiring. Regenerated by pocketkit gen on every dev run.
pocketkit_gen.go

.DS_Store
.env
.env.*
!.env.example
`

const tmplReadme = "# %s\n\n" + `Built with [pocketkit](https://github.com/Ovi1kanobe/pocketkit).

## Develop

    go mod tidy
    pocketkit dev

This regenerates route wiring, starts PocketBase on :8090, and runs the
SvelteKit dev server on :5173 with '/api' proxied to PocketBase.

## Sign-in

Auth is OIDC-only -- password login is disabled and cannot be re-enabled from
the dashboard. Point the OIDC provider at your Rauthy instance in the superuser
dashboard under **Collections > users > Options > OAuth2 > OpenID Connect**.

## Routes

    pocketkit routes

Add one by creating a file:

    api/things/GET.go        ->  GET  /api/things
    api/things/_id/GET.go    ->  GET  /api/things/{id}

## Types

    pocketkit types

Regenerates 'frontend/src/lib/pocketbase-types.ts' from the local database.
`

const tmplSvelteConfig = `import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
export default {
	preprocess: vitePreprocess(),
	kit: {
		// PocketBase serves this directory. The SPA fallback lets PocketBase
		// hand any unmatched path to the client router.
		adapter: adapter({
			pages: 'build',
			assets: 'build',
			fallback: 'index.html',
			precompress: false,
			strict: false
		})
	}
};
`

const tmplViteConfig = `import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

// In production PocketBase serves the built frontend, so the API is same-origin.
// The dev proxy reproduces that, which keeps auth cookies working in both.
const POCKETBASE = 'http://127.0.0.1:8090';

export default defineConfig({
	plugins: [sveltekit()],
	server: {
		proxy: {
			'/api': { target: POCKETBASE, changeOrigin: true },
			'/_': { target: POCKETBASE, changeOrigin: true }
		}
	}
});
`

const tmplLayoutTS = `// pocketkit ships a single-page app: PocketBase serves static files and the
// client talks to the API directly, so there is no server to render on.
export const ssr = false;
export const prerender = false;
`

const tmplPBClient = `import PocketBase from 'pocketbase';
import type { TypedPocketBase } from './pocketbase-types';

// Same-origin in production and, thanks to the Vite proxy, in development too.
export const pb = new PocketBase(window.location.origin) as TypedPocketBase;

// Auth is OIDC-only. There is deliberately no password sign-in helper here.
export function signIn(collection = 'users') {
	return pb.collection(collection).authWithOAuth2({ provider: 'oidc' });
}

export function signOut() {
	pb.authStore.clear();
}
`
